### PR TITLE
124 improve comment sidebar styling

### LINKED ISSUE #124: Platform: Comment sidebar styling issues
I identified 3 issues with the comment sidebar:
- [x] issue 1: header overflow breaks layout
<details>

As can be seen from in [scripture-editors codesandbox](https://codesandbox.io/p/github/BiblioNexus-Foundation/scripture-editors/main) the `<h2 class="CommentPlugin_CommentsPanel_Heading">Comments</h2>` overflows the comment container.
grafik

In Platform.Bible this causes a "right hand" overflow, that produces a vertical scroll bar:
grafik

Which can also be seen in the codesandbox:
grafik

It is fixed by removing `width: 100%` from `.CommentPlugin_CommentsPanel_Heading`
</details>

- [x] issue 2: header text is clipped
<details>

See pictures below.

`.CommentPlugin_CommentsPanel_Heading` should get
```css
text-overflow: ellipsis; /* clip the header text */
padding: 16px /* have symetric padding in a 2^n grid value */
/* remove height: 34px; */
/* you may or may not want to add line-height: 16px, as the font itself seems to create some additional whitespace */
```
Now also remove the `top: 45px` from `.CommentPlugin_CommentsPanel_List`

Before:
grafik

After:
grafik
</details>

- [x] issue 3: placeholder text "No Comments" is not visible
<details>

`position: absolute` should be removed from `.CommentPlugin_CommentsPanel_Heading`

with `position: absolute`
grafik

when removing `position: absolute`
grafik

Removing it seems not to have a negative impact on the comment list
grafik

</details>

### PR DESCRIPTION
**Pull request by irahopkinson**
- fixes #124

### CODE REVIEW

**Comment by irahopkinson** [comment]
@Sebastian-ubs thanks for detailing this in #124. Would appreciate your code review. You can test this in [CodeSandbox](https://codesandbox.io/p/github/BiblioNexus-Foundation/scripture-editors/sidebar-styling).

**Review by Sebastian-ubs — APPROVED** [review]
The changes look good in code
- although codebox for me seems not to pick up those and so still uses a 15px padding-left besides showing it would run from your branch 🤷
So I am not able to test it

**Comment by irahopkinson** [comment]
It worked when I tested it there. Did you click on the link I provide in my last post as that checks out the branch these changes are made on (since the code isn't merged to **main** yet)?

**Comment by irahopkinson** [comment]
@Sebastian-ubs ah, that link won't work for you because there is a pending invite to the CodeSandbox workspace for you (it was sent quite some time ago so trawl your inbox). You need to accept that and be logged in to see the latest changes. You have probably been missing all kinds of the latest changes.

**Comment by Sebastian-ubs** [comment]
Thank you Ira, I have clicke the link. Will see if it changes anything for new branches. At least I can see those changes on the codesandbox master now.

**Pull request merged**
